### ISSUE TITLE
See peers in AdGuard 

### ISSUE THREAD

**Issue by lavir** [naazf/docker-adguard-unbound-wireguard#4]
Hi there,
thank you for the docker-compose file.

I have a question. Is it possible to set up (change unbound config/PostUp/PostDown ) so to see peers as clients (10.6.0.0) in AdGuard instead of the Wireguard server (10.2.0.3)?

<img width="577" alt="CleanShot 2022-04-06 at 11 04 40@2x" src="https://user-images.githubusercontent.com/1274746/161926428-daf334c5-1d56-4723-be0f-3fd385b6f5f2.png">

**Comment by fnazz** [comment]
Yes, Im assuming  you are referring to change the network range here, you will have to update the subnet range from 
- private-network : 10.2.0.0/24
to
- private-network: 10.6.0.0/24

Then change corresponding sections where ip's are hard set.

**Comment by lavir** [comment]
Unfortunately it does not work, or I did something wrong.
Below is my docker compose file
```
networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/24

services:
  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      private_network:
        ipv4_address: 10.6.0.200


  wireguard:
    depends_on: [unbound, adguard]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERPORT=51820
      # - SERVERURL=vpn.example.com #optional - For use with DDNS (Uncomment to use)
      - PEERS=1 # How many peers to generate for you (clients)
      - PEERDNS=10.6.0.100 # Set it to point to adguard home
      - INTERNAL_SUBNET=10.6.0.0
      #- ALLOWEDIPS=10.6.0.0/24 # optional - split tunnel for web panel and DNS traffic only
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.6.0.3


  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work"
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.6.0.100
```
